spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "kakitani2000@gmail.com"
    password: "dsfdf"
    protocol: "smtp"
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
      debug: true

  org:
    jobrunr:
      background-job-server:
        enabled: true
        worker-count: 5
      dashboard:
        enabled: true
        port: 8001

  data:
    redis:
      host: localhost
      port: 6379
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    url: jdbc:mysql://localhost:3309/myapp
    username: myuser
    password: mypass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
  liquibase:
    enabled: true
    drop-first: false
    contexts: dev
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    root: TRACE
    org.springframework: INFO
    com.farukgenc.boilerplate.springboot: INFO
    liquibase: DEBUG

jwt:
  secretKey: secretKey
  issuer: issuer
  expirationMinute: 60

app:
  file-storage:
    upload-dir: ./uploads
